[environment]
cwd="~/Videos"

[data]
files_command = "eza -1 --no-quotes | grep mp4"

commands = [
  """eza -1 --no-quotes | grep mp4""",
  """eza -1 /nosuchdirectory""",
]

header = [
  "file",
  "empty column"
]
